name: Docker Build and Push

on:
  push:
    branches:
      - main  # Запускать workflow при push в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверяем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить Docker для авторизации в Docker Hub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Берем имя пользователя из секретов
          password: ${{ secrets.DOCKER_PASSWORD }}   # Берем пароль из секретов

      # Шаг 3: Собираем Docker образ
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest .

      # Шаг 4: Пушим образ в Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
